import type { ImageLoaderProps } from 'next/image';

export const cloudinaryImageDeliveries = {
  thumbnail: { maximumWidth: 300, quality: 'eco' },
  'product-card': { maximumWidth: 900, quality: 'good' },
  'product-detail': { maximumWidth: 1400, quality: 'good' },
} as const;

export type CloudinaryImageDelivery = keyof typeof cloudinaryImageDeliveries;

type CloudinaryProductImageOptions = {
  delivery: CloudinaryImageDelivery;
  width?: number;
};

const cloudinaryVersionPattern = /^v\d+$/;
const managedTransformationPattern = /^(?:f_auto|q_auto(?::(?:good|eco))?|c_limit|w_\d+)(?:,(?:f_auto|q_auto(?::(?:good|eco))?|c_limit|w_\d+))*$/;
const managedFormatOrQualityPattern = /^(?:f_auto|q_auto(?::(?:good|eco))?)$/;
const managedDeliverySegmentPattern = /^f_auto,q_auto:(?:good|eco),c_limit,w_\d+$/;

export function isCloudinaryImageUrl(src: string): boolean {
  try {
    const url = new URL(src);
    const pathSegments = url.pathname.split('/').filter(Boolean);

    return (
      url.protocol === 'https:' &&
      url.hostname === 'res.cloudinary.com' &&
      pathSegments.length >= 4 &&
      pathSegments[1] === 'image' &&
      pathSegments[2] === 'upload'
    );
  } catch {
    return false;
  }
}

function deliveryWidth(delivery: CloudinaryImageDelivery, requestedWidth?: number): number {
  const maximumWidth = cloudinaryImageDeliveries[delivery].maximumWidth;

  if (!requestedWidth || !Number.isFinite(requestedWidth)) {
    return maximumWidth;
  }

  return Math.min(Math.max(Math.round(requestedWidth), 1), maximumWidth);
}

function normalizeTransformationSegments(segments: string[]): string[] {
  return segments.flatMap((segment) => {
    if (managedTransformationPattern.test(segment)) {
      return [];
    }

    const values = segment.split(',');
    const hasManagedFormatOrQuality = values.some((value) => managedFormatOrQualityPattern.test(value));

    if (!hasManagedFormatOrQuality) {
      return [segment];
    }

    // This segment is known to be before a version marker, so it is a
    // transformation rather than part of the public ID. Keep crop settings,
    // but let the centralized delivery segment own format, quality, and c_limit.
    const normalized = values.filter(
      (value) => managedFormatOrQualityPattern.test(value) === false && value !== 'c_limit',
    );

    return normalized.length ? [normalized.join(',')] : [];
  });
}

function splitCloudinaryDeliveryPath(segments: string[]): string[] {
  const versionIndex = segments.findIndex((segment) => cloudinaryVersionPattern.test(segment));

  if (versionIndex >= 0) {
    // Cloudinary's version marker cleanly separates transformations from the
    // public ID. Never inspect any segment at or after this boundary.
    return [
      ...normalizeTransformationSegments(segments.slice(0, versionIndex)),
      ...segments.slice(versionIndex),
    ];
  }

  // Without a version marker, transformation and public-ID folders are
  // ambiguous. Only remove the exact canonical segment generated by this
  // helper at the beginning of the path; preserve every other path segment.
  if (segments[0] && managedDeliverySegmentPattern.test(segments[0])) {
    return segments.slice(1);
  }

  return segments;
}

/**
 * Adds one deterministic delivery-only transformation to a Cloudinary upload URL.
 * Existing transformations (including crop settings) are retained, while a previous
 * transformation created by this helper is replaced to avoid duplicate parameters.
 */
export function getCloudinaryProductImageUrl(
  src: string,
  { delivery, width }: CloudinaryProductImageOptions,
): string {
  if (!isCloudinaryImageUrl(src)) {
    return src;
  }

  const url = new URL(src);
  const pathSegments = url.pathname.split('/').filter(Boolean);
  const uploadIndex = pathSegments.findIndex(
    (segment, index) => segment === 'upload' && pathSegments[index - 1] === 'image',
  );

  if (uploadIndex === -1) {
    return src;
  }

  const transformation = [
    'f_auto',
    `q_auto:${cloudinaryImageDeliveries[delivery].quality}`,
    'c_limit',
    `w_${deliveryWidth(delivery, width)}`,
  ].join(',');

  const remainingSegments = splitCloudinaryDeliveryPath(pathSegments.slice(uploadIndex + 1));

  url.pathname = [
    ...pathSegments.slice(0, uploadIndex + 1),
    transformation,
    ...remainingSegments,
  ].join('/');

  return url.toString();
}

export function createCloudinaryProductImageLoader(
  delivery: CloudinaryImageDelivery,
) {
  return ({ src, width }: ImageLoaderProps): string =>
    getCloudinaryProductImageUrl(src, { delivery, width });
}
